### ISSUE TITLE
Cannot Build This Project By Qt5.9.1 VS2015

### ISSUE THREAD

**Issue by toby20130333** [bnogalm/StellarQtSDK#1]

**Comment by bnogalm** [comment]
I am currently using Qt5.9.3 MinGW for Windows. It should also work in VS as i don't remember using any GCC macro magic, maybe a later version for a more complete C++11 support. It may be a SFINAE expression i am using.
Try VS2017, but i recommend mingw, so what ever you do, it will be for sure compiling for other platforms.

**Comment by toby20130333** [comment]
ok i got it and modify some code ，build it ok thank you




发自网易邮箱大师
On 01/03/2018 17:06, bnogalm wrote:

I am currently using Qt5.9.3 MinGW for Windows. It should also work in VS as i don't remember using any GCC macro magic, maybe a later version for a more complete C++11 support. It may be a SFINAE expression i am using.
Try VS2017, but i recommend mingw, so what ever you do, it will be for sure compiling for other platforms.

**Comment by toby20130333** [comment]
@bnogalm Do you hava stellar wallet address?

**Comment by toby20130333** [comment]
I sovle it beacuse compiler diff
