### ISSUE TITLE
Help with tx_faile dmessage

### ISSUE THREAD

**Issue by munawarb** [bnogalm/StellarQtSDK#12]
First, thanks so much for providing this SDK! I have one issue with it.

When I submit a data operation, Stellar returns a tx_failed message.

I'm running a local Horizon server along with a local stellar node. Both are connecting to each other fine.

Here is my code:
```
#include <iostream>
#include <QCoreApplication>
#include <QObject.h>
#include <keypair.h>
#include <network.h>
#include <server.h>
#include <responses/accountresponse.h>
#include <xdr/stellartypes.h>
#include <account.h>
#include <transaction.h>
#include <managedataoperation.h>
#include <responses/submittransactionresponse.h>
#include <createaccountoperation.h>
using namespace std;
int main(int argc, char *argv[])
{
	QCoreApplication a(argc, argv);
	
	KeyPair* accountAddress = KeyPair::fromSecretSeed((QString)"SBZOJVX2YEUACZW5T3K62YIF7DZQFDEEKFE5S4QFOHMZX3VFARVOY2ED");
	Network::useMyNetwork();//select the network to use, just changed the passphrase
	Server * server = new Server("http://localhost:8000");
	AccountResponse * response = server->accounts().account(accountAddress);
	cout << "Connecting..." << endl;
	QObject::connect(response, &AccountResponse::ready, [response]() {
		if (response->accountID().isEmpty()) {
			//accountNotFundedYet
		}
		//response contains account data
	});
	//First you should refresh the account data to get the last secuence number.
	AccountResponse * selfAccountResponse = server->accounts().account(accountAddress); // This call works, and I get account data
	KeyPair *source = KeyPair::fromAccountId(accountAddress->getAccountId());//we require a copy
	cout << "Account address is " << accountAddress->getAccountId().toStdString() << endl;
	qint64 sequenceNumber = selfAccountResponse->getSequenceNumber();
	cout << "sequence number is ";
	cout << sequenceNumber << endl;
	Account* account = new Account(source, sequenceNumber);
	Transaction::Builder *builder = new Transaction::Builder(account);
	builder->addOperation(new ManageDataOperation("test", "hi"));
	Transaction* transaction = builder->build();
	transaction->sign(accountAddress);
	QObject::connect(server, &Server::transactionResponse, [](SubmitTransactionResponse* resp) {
		cout << "something cool happend" << endl;
	});
	QObject::connect(server, &Server::transactionError, []() {
		cout << "Something went wrong!" << endl;
	});
	cout << "Submitting..." << endl;
	server->submitTransaction(transaction); // returns 400.
	return a.exec();

}
```

Next, here is my code output:

C:\Users\munawar\test_stellar\debug>StellarQtSDK.exe
Attaching...
1
Connecting...
Attaching...
1
Account address is GBKOA6YMQKPO4XY6GODXTPKQ7EWLJ4DCBYKDY2E7QJHSOYBLLN6G3Y2U
sequence number is 0
Submitting...
Attaching...
1
Got finish event
QUERY :  QUrl("http://localhost:8000/accounts/GBKOA6YMQKPO4XY6GODXTPKQ7EWLJ4DCBYKDY2E7QJHSOYBLLN6G3Y2U")
RESPONSE :  "{\n  \"_links\": {\n    \"self\": {\n      \"href\": \"http://localhost:8000/accounts/GBKOA6YMQKPO4XY6GODXTPKQ7EWLJ4DCBYKDY2E7QJHSOYBLLN6G3Y2U\"\n    },\n    \"transactions\": {\n      \"href\": \"http://localhost:8000/accounts/GBKOA6YMQKPO4XY6GODXTPKQ7EWLJ4DCBYKDY2E7QJHSOYBLLN6G3Y2U/transactions{?cursor,limit,order}\",\n      \"templated\": true\n    },\n    \"operations\": {\n      \"href\": \"http://localhost:8000/accounts/GBKOA6YMQKPO4XY6GODXTPKQ7EWLJ4DCBYKDY2E7QJHSOYBLLN6G3Y2U/operations{?cursor,limit,order}\",\n      \"templated\": true\n    },\n    \"payments\": {\n      \"href\": \"http://localhost:8000/accounts/GBKOA6YMQKPO4XY6GODXTPKQ7EWLJ4DCBYKDY2E7QJHSOYBLLN6G3Y2U/payments{?cursor,limit,order}\",\n      \"templated\": true\n    },\n    \"effects\": {\n      \"href\": \"http://localhost:8000/accounts/GBKOA6YMQKPO4XY6GODXTPKQ7EWLJ4DCBYKDY2E7QJHSOYBLLN6G3Y2U/effects{?cursor,limit,order}\",\n      \"templated\": true\n    },\n    \"offers\": {\n      \"href\": \"http://localhost:8000/accounts/GBKOA6YMQKPO4XY6GODXTPKQ7EWLJ4DCBYKDY2E7QJHSOYBLLN6G3Y2U/offers{?cursor,limit,order}\",\n      \"templated\": true\n    },\n    \"trades\": {\n      \"href\": \"http://localhost:8000/accounts/GBKOA6YMQKPO4XY6GODXTPKQ7EWLJ4DCBYKDY2E7QJHSOYBLLN6G3Y2U/trades{?cursor,limit,order}\",\n      \"templated\": true\n    },\n    \"data\": {\n      \"href\": \"http://localhost:8000/accounts/GBKOA6YMQKPO4XY6GODXTPKQ7EWLJ4DCBYKDY2E7QJHSOYBLLN6G3Y2U/data/{key}\",\n      \"templated\": true\n    }\n  },\n  \"id\": \"GBKOA6YMQKPO4XY6GODXTPKQ7EWLJ4DCBYKDY2E7QJHSOYBLLN6G3Y2U\",\n  \"paging_token\": \"\",\n  \"account_id\": \"GBKOA6YMQKPO4XY6GODXTPKQ7EWLJ4DCBYKDY2E7QJHSOYBLLN6G3Y2U\",\n  \"sequence\": \"0\",\n  \"subentry_count\": 0,\n  \"home_domain\": \"0\",\n  \"thresholds\": {\n    \"low_threshold\": 0,\n    \"med_threshold\": 0,\n    \"high_threshold\": 0\n  },\n  \"flags\": {\n    \"auth_required\": false,\n    \"auth_revocable\": false\n  },\n  \"balances\": [\n    {\n      \"balance\": \"100000000000.0000000\",\n      \"asset_type\": \"native\"\n    }\n  ],\n  \"signers\": [\n    {\n      \"public_key\": \"GBKOA6YMQKPO4XY6GODXTPKQ7EWLJ4DCBYKDY2E7QJHSOYBLLN6G3Y2U\",\n      \"weight\": 1,\n      \"key\": \"GBKOA6YMQKPO4XY6GODXTPKQ7EWLJ4DCBYKDY2E7QJHSOYBLLN6G3Y2U\",\n      \"type\": \"ed25519_public_key\"\n    },\n    {\n      \"public_key\": \"GBKOA6YMQKPO4XY6GODXTPKQ7EWLJ4DCBYKDY2E7QJHSOYBLLN6G3Y2U\",\n      \"weight\": 1,\n      \"key\": \"GBKOA6YMQKPO4XY6GODXTPKQ7EWLJ4DCBYKDY2E7QJHSOYBLLN6G3Y2U\",\n      \"type\": \"ed25519_public_key\"\n    }\n  ],\n  \"data\": {}\n}"
Error code is
QNetworkReply::NetworkError(NoError)

And error is  "Unknown error"

Got finish event
QUERY :  QUrl("http://localhost:8000/accounts/GBKOA6YMQKPO4XY6GODXTPKQ7EWLJ4DCBYKDY2E7QJHSOYBLLN6G3Y2U")
RESPONSE :  "{\n  \"_links\": {\n    \"self\": {\n      \"href\": \"http://localhost:8000/accounts/GBKOA6YMQKPO4XY6GODXTPKQ7EWLJ4DCBYKDY2E7QJHSOYBLLN6G3Y2U\"\n    },\n    \"transactions\": {\n      \"href\": \"http://localhost:8000/accounts/GBKOA6YMQKPO4XY6GODXTPKQ7EWLJ4DCBYKDY2E7QJHSOYBLLN6G3Y2U/transactions{?cursor,limit,order}\",\n      \"templated\": true\n    },\n    \"operations\": {\n      \"href\": \"http://localhost:8000/accounts/GBKOA6YMQKPO4XY6GODXTPKQ7EWLJ4DCBYKDY2E7QJHSOYBLLN6G3Y2U/operations{?cursor,limit,order}\",\n      \"templated\": true\n    },\n    \"payments\": {\n      \"href\": \"http://localhost:8000/accounts/GBKOA6YMQKPO4XY6GODXTPKQ7EWLJ4DCBYKDY2E7QJHSOYBLLN6G3Y2U/payments{?cursor,limit,order}\",\n      \"templated\": true\n    },\n    \"effects\": {\n      \"href\": \"http://localhost:8000/accounts/GBKOA6YMQKPO4XY6GODXTPKQ7EWLJ4DCBYKDY2E7QJHSOYBLLN6G3Y2U/effects{?cursor,limit,order}\",\n      \"templated\": true\n    },\n    \"offers\": {\n      \"href\": \"http://localhost:8000/accounts/GBKOA6YMQKPO4XY6GODXTPKQ7EWLJ4DCBYKDY2E7QJHSOYBLLN6G3Y2U/offers{?cursor,limit,order}\",\n      \"templated\": true\n    },\n    \"trades\": {\n      \"href\": \"http://localhost:8000/accounts/GBKOA6YMQKPO4XY6GODXTPKQ7EWLJ4DCBYKDY2E7QJHSOYBLLN6G3Y2U/trades{?cursor,limit,order}\",\n      \"templated\": true\n    },\n    \"data\": {\n      \"href\": \"http://localhost:8000/accounts/GBKOA6YMQKPO4XY6GODXTPKQ7EWLJ4DCBYKDY2E7QJHSOYBLLN6G3Y2U/data/{key}\",\n      \"templated\": true\n    }\n  },\n  \"id\": \"GBKOA6YMQKPO4XY6GODXTPKQ7EWLJ4DCBYKDY2E7QJHSOYBLLN6G3Y2U\",\n  \"paging_token\": \"\",\n  \"account_id\": \"GBKOA6YMQKPO4XY6GODXTPKQ7EWLJ4DCBYKDY2E7QJHSOYBLLN6G3Y2U\",\n  \"sequence\": \"0\",\n  \"subentry_count\": 0,\n  \"home_domain\": \"0\",\n  \"thresholds\": {\n    \"low_threshold\": 0,\n    \"med_threshold\": 0,\n    \"high_threshold\": 0\n  },\n  \"flags\": {\n    \"auth_required\": false,\n    \"auth_revocable\": false\n  },\n  \"balances\": [\n    {\n      \"balance\": \"100000000000.0000000\",\n      \"asset_type\": \"native\"\n    }\n  ],\n  \"signers\": [\n    {\n      \"public_key\": \"GBKOA6YMQKPO4XY6GODXTPKQ7EWLJ4DCBYKDY2E7QJHSOYBLLN6G3Y2U\",\n      \"weight\": 1,\n      \"key\": \"GBKOA6YMQKPO4XY6GODXTPKQ7EWLJ4DCBYKDY2E7QJHSOYBLLN6G3Y2U\",\n      \"type\": \"ed25519_public_key\"\n    },\n    {\n      \"public_key\": \"GBKOA6YMQKPO4XY6GODXTPKQ7EWLJ4DCBYKDY2E7QJHSOYBLLN6G3Y2U\",\n      \"weight\": 1,\n      \"key\": \"GBKOA6YMQKPO4XY6GODXTPKQ7EWLJ4DCBYKDY2E7QJHSOYBLLN6G3Y2U\",\n      \"type\": \"ed25519_public_key\"\n    }\n  ],\n  \"data\": {}\n}"
Error code is
QNetworkReply::NetworkError(NoError)

And error is  "Unknown error"

Got finish event

//Here is where the code fails
QUERY :  QUrl("http://localhost:8000/transactions")
RESPONSE :  "{\n  \"type\": \"https://stellar.org/horizon-errors/transaction_failed\",\n  \"title\": \"Transaction Failed\",\n  \"status\": 400,\n  \"detail\": \"The transaction failed when submitted to the stellar network. The `extras.result_codes` field on this response contains further details.  Descriptions of each code can be found at: https://www.stellar.org/developers/learn/concepts/list-of-operations.html\",\n  \"extras\": {\n    \"envelope_xdr\": \"AAAAAFTgewyCnu5fHjOHeb1Q+Sy08GIOFDxon4JPJ2ArW3xtAAAAyAAAAAAAAAABAAAAAAAAAAAAAAACAAAAAAAAAAoAAAAEdGVzdAAAAAEAAAACaGkAAAAAAAAAAAAAAAAAAFCGE6kUb7YtWc+xJTAqCU7ZXDM5ojbOp/gRgKcE8/TUAAAJGE5yoAAAAAAAAAAAAStbfG0AAABAstNjPIz4Gh3buGQdtgDXklT/LFrgQkPHUsjwIjwyKMIRxh5HMhuvOigOUzNv15rqHeIut4Iiy1TMhXD64S0DDg==\",\n    \"result_codes\": {\n      \"transaction\": \"tx_failed\",\n      \"operations\": [\n        \"\",\n        \"\"\n      ]\n    },\n    \"result_xdr\": \"AAAAAAAAAMj/////AAAAAgAAAAAAAAAK/////wAAAAAAAAAAAAAAAAAAAAA=\"\n  }\n}"
Error code is
QNetworkReply::NetworkError(ProtocolInvalidOperationError)

And error is  "Error transferring http://localhost:8000/transactions - server replied: Bad Request"

"Error transferring http://localhost:8000/transactions - server replied: Bad Request"
Got error!
Something went wrong!

Do you have any pointers as to why this might be happening? I'm using stellar-core 9.2.

**Comment by bnogalm** [comment]
Thx, i love to see someone is trying to use it :)

All the requests are async, to be able to build responsible apps.
As example i used lambda functions as slots, but you can use your own object slots.

sequence number shouldn't be zero. It is zero because it will be ready later, so everything after 

	//First you should refresh the account data to get the last secuence number.


should go inside 

//response contains account data

of course, you dont need a second request to refresh accountdata.



Any question, just ask :)

**Comment by munawarb** [comment]
Hi @bnogalm,
Definitely! It is a great API for those of us who prefer C++ :) you've done a great job with it! I was sad at first when I didn't find a C++ API of the SDK and then I came across your Github and was impressed at what you've done.

Ok, so I've wrapped the code inside the initial call to get account. Here is my new code:
```
#include <iostream>
#include <QCoreApplication>
#include <QObject.h>
#include <keypair.h>
#include <network.h>
#include <server.h>
#include <responses/accountresponse.h>
#include <xdr/stellartypes.h>
#include <account.h>
#include <transaction.h>
#include <managedataoperation.h>
#include <responses/submittransactionresponse.h>
#include <createaccountoperation.h>
using namespace std;
int main(int argc, char *argv[])
{
	QCoreApplication a(argc, argv);

	KeyPair* accountAddress = KeyPair::fromSecretSeed((QString)"SBZOJVX2YEUACZW5T3K62YIF7DZQFDEEKFE5S4QFOHMZX3VFARVOY2ED");
	Network::useMyNetwork();//select the network to use, just changed the passphrase
	Server * server = new Server("http://localhost:8000");
	AccountResponse * response = server->accounts().account(accountAddress);
	cout << "Connecting..." << endl;
	QObject::connect(response, &AccountResponse::ready, [response, server, accountAddress]() {
		if (response->accountID().isEmpty()) {
			//accountNotFundedYet
			cout << "Account not funded!" << endl;
		}
		//response contains account data
		KeyPair *source = KeyPair::fromAccountId(accountAddress->getAccountId());//we require a copy
		cout << "Account address is " << accountAddress->getAccountId().toStdString() << endl;
		qint64 sequenceNumber = response->getSequenceNumber();
		cout << "sequence number is ";
		cout << sequenceNumber << endl;
		Account* account = new Account(source, sequenceNumber);
		Transaction::Builder *builder = new Transaction::Builder(account);
		builder->addOperation(new ManageDataOperation("test", "hi"));
		Transaction* transaction = builder->build();
		transaction->sign(accountAddress);
		QObject::connect(server, &Server::transactionResponse, [](SubmitTransactionResponse* resp) {
			cout << "something cool happend" << endl;
		});
		QObject::connect(server, &Server::transactionError, []() {
			cout << "Something went wrong!" << endl;
		});
		cout << "Submitting..." << endl;
		server->submitTransaction(transaction); // returns 400.

	});
	return a.exec();

}
```

Unfortunately, I still get the same sequence number of 0. I've noticed in the response, the result is just "" where there should be something like tx_bad_seq, here:
{\n      \"transaction\": \"tx_failed\",\n      \"operations\": [\n        \"\"\n      ]\n

I hope you can help me to resolve this issue. I've been working on it for some time now and can't seem to get anywhere.

Here is the full output:
```
Attaching...
1
Connecting...
Got finish event
QUERY :  QUrl("http://localhost:8000/accounts/GBKOA6YMQKPO4XY6GODXTPKQ7EWLJ4DCBYKDY2E7QJHSOYBLLN6G3Y2U")
RESPONSE :  "{\n  \"_links\": {\n    \"self\": {\n      \"href\": \"http://localhost:8000/accounts/GBKOA6YMQKPO4XY6GODXTPKQ7EWLJ4DCBYKDY2E7QJHSOYBLLN6G3Y2U\"\n    },\n    \"transactions\": {\n      \"href\": \"http://localhost:8000/accounts/GBKOA6YMQKPO4XY6GODXTPKQ7EWLJ4DCBYKDY2E7QJHSOYBLLN6G3Y2U/transactions{?cursor,limit,order}\",\n      \"templated\": true\n    },\n    \"operations\": {\n      \"href\": \"http://localhost:8000/accounts/GBKOA6YMQKPO4XY6GODXTPKQ7EWLJ4DCBYKDY2E7QJHSOYBLLN6G3Y2U/operations{?cursor,limit,order}\",\n      \"templated\": true\n    },\n    \"payments\": {\n      \"href\": \"http://localhost:8000/accounts/GBKOA6YMQKPO4XY6GODXTPKQ7EWLJ4DCBYKDY2E7QJHSOYBLLN6G3Y2U/payments{?cursor,limit,order}\",\n      \"templated\": true\n    },\n    \"effects\": {\n      \"href\": \"http://localhost:8000/accounts/GBKOA6YMQKPO4XY6GODXTPKQ7EWLJ4DCBYKDY2E7QJHSOYBLLN6G3Y2U/effects{?cursor,limit,order}\",\n      \"templated\": true\n    },\n    \"offers\": {\n      \"href\": \"http://localhost:8000/accounts/GBKOA6YMQKPO4XY6GODXTPKQ7EWLJ4DCBYKDY2E7QJHSOYBLLN6G3Y2U/offers{?cursor,limit,order}\",\n      \"templated\": true\n    },\n    \"trades\": {\n      \"href\": \"http://localhost:8000/accounts/GBKOA6YMQKPO4XY6GODXTPKQ7EWLJ4DCBYKDY2E7QJHSOYBLLN6G3Y2U/trades{?cursor,limit,order}\",\n      \"templated\": true\n    },\n    \"data\": {\n      \"href\": \"http://localhost:8000/accounts/GBKOA6YMQKPO4XY6GODXTPKQ7EWLJ4DCBYKDY2E7QJHSOYBLLN6G3Y2U/data/{key}\",\n      \"templated\": true\n    }\n  },\n  \"id\": \"GBKOA6YMQKPO4XY6GODXTPKQ7EWLJ4DCBYKDY2E7QJHSOYBLLN6G3Y2U\",\n  \"paging_token\": \"\",\n  \"account_id\": \"GBKOA6YMQKPO4XY6GODXTPKQ7EWLJ4DCBYKDY2E7QJHSOYBLLN6G3Y2U\",\n  \"sequence\": \"0\",\n  \"subentry_count\": 0,\n  \"home_domain\": \"0\",\n  \"thresholds\": {\n    \"low_threshold\": 0,\n    \"med_threshold\": 0,\n    \"high_threshold\": 0\n  },\n  \"flags\": {\n    \"auth_required\": false,\n    \"auth_revocable\": false\n  },\n  \"balances\": [\n    {\n      \"balance\": \"100000000000.0000000\",\n      \"asset_type\": \"native\"\n    }\n  ],\n  \"signers\": [\n    {\n      \"public_key\": \"GBKOA6YMQKPO4XY6GODXTPKQ7EWLJ4DCBYKDY2E7QJHSOYBLLN6G3Y2U\",\n      \"weight\": 1,\n      \"key\": \"GBKOA6YMQKPO4XY6GODXTPKQ7EWLJ4DCBYKDY2E7QJHSOYBLLN6G3Y2U\",\n      \"type\": \"ed25519_public_key\"\n    },\n    {\n      \"public_key\": \"GBKOA6YMQKPO4XY6GODXTPKQ7EWLJ4DCBYKDY2E7QJHSOYBLLN6G3Y2U\",\n      \"weight\": 1,\n      \"key\": \"GBKOA6YMQKPO4XY6GODXTPKQ7EWLJ4DCBYKDY2E7QJHSOYBLLN6G3Y2U\",\n      \"type\": \"ed25519_public_key\"\n    }\n  ],\n  \"data\": {}\n}"
Error code is
QNetworkReply::NetworkError(NoError)

And error is  "Unknown error"

Account address is GBKOA6YMQKPO4XY6GODXTPKQ7EWLJ4DCBYKDY2E7QJHSOYBLLN6G3Y2U
sequence number is 0
Submitting...
Attaching...
1
Got finish event
QUERY :  QUrl("http://localhost:8000/transactions")
RESPONSE :  "{\n  \"type\": \"https://stellar.org/horizon-errors/transaction_failed\",\n  \"title\": \"Transaction Failed\",\n  \"status\": 400,\n  \"detail\": \"The transaction failed when submitted to the stellar network. The `extras.result_codes` field on this response contains further details.  Descriptions of each code can be found at: https://www.stellar.org/developers/learn/concepts/list-of-operations.html\",\n  \"extras\": {\n    \"envelope_xdr\": \"AAAAAFTgewyCnu5fHjOHeb1Q+Sy08GIOFDxon4JPJ2ArW3xtAAAAZAAAAAAAAAABAAAAAAAAAAAAAAABAAAAAAAAAAoAAAAEdGVzdAAAAAEAAAACaGkAAAAAAAAAAAABK1t8bQAAAEAoqpLmWDs9DZvXovLhmVImcp8zkzzPE9UazhrRrlBWVorJjNGoriDTe9+D4Tqb/5SlwmtQ2esT11Z9lNF7N4kB\",\n    \"result_codes\": {\n      \"transaction\": \"tx_failed\",\n      \"operations\": [\n        \"\"\n      ]\n    },\n    \"result_xdr\": \"AAAAAAAAAGT/////AAAAAQAAAAAAAAAK/////wAAAAA=\"\n  }\n}"
Error code is
QNetworkReply::NetworkError(ProtocolInvalidOperationError)

And error is  "Error transferring http://localhost:8000/transactions - server replied: Bad Request"

"Error transferring http://localhost:8000/transactions - server replied: Bad Request"
Got error!
Something went wrong!
```

**Comment by munawarb** [comment]
Hi @bnogalm,
I tried to connect to testnet, and the data operation went through successfully :) so it seems like it's definitely an issue on my end. However, now I know it's got to do with my setup and not the code. I'll keep working on it and post back here when I get it resolved locally. Thanks for your help!

I downloaded and compiled stellar-core, and then downloaded the Horizon binary and ran it. This is how I'm running it locally, using this guide: https://github.com/stellar/stellar-core/blob/master/INSTALL.md and this guide: https://github.com/stellar/horizon.

The issue I had is that since I'm not running on the public testnet, I didn't have access to the Testnet Friendbot, so I had to modify my Postgresql tables manually to create an account. So, I think there's something going on there that I need to check.

**Comment by munawarb** [comment]
It turns out I wasn't understanding the "protocol" distinction that Stellar makes. Just because you download the latest build, doesn't mean you're running the latest protocol. I had to upgrade my Stellar-Core to protocol 9 by issuing this command: `stellar-core -c 'upgrades?mode=set&upgradetime=yyyy-mm-ddThh:mm:ss&protocolversion=9'`.

This command upgrades the protocol for stand-alone networks and votes on the upgrade for networks that are not stand-alone. So, after Core upgraded the protocol, it worked fine.
