### ISSUE TITLE
Converting base64-encoded string back into a transaction result

### ISSUE THREAD

**Issue by munawarb** [bnogalm/StellarQtSDK#13]
Hi,
In the Javascript SDK, we're able to take a base64-encoded reply from stellar-core and convert it to JSON to get hashes and all that, if we'd like to interface to stellar-core directly and bypass Horizon.

Can I do such a thing with the C++ SDK? I see methods to convert to EnvelopeXDR and to base64, but can I do the reverse? As in, given a base64 string from stellar-core, convert it into a `SubmitTransactionResponse` so that I can use methods like `getHash()` to extract the data?

**Comment by bnogalm** [comment]
Hello,

I didn't see that method in the Java SDK when i implemented it. So to make possible sign transactions offline in my wallet (functionality available in the Beta version) i added some methods to deserialize a transaction and an xdr envelope

Could be a nice addition to add easier methods to do this.

You can actually read binary xdr like this:
`
        QByteArray data; //data containing a binary xdr transaction
        stellar::Transaction transaction;
        QDataStream stream(&data,QIODevice::ReadOnly);
        stream >> transaction;

        Transaction *transactionObject = Transaction::fromXdr(transaction);
`

To read a signed transaction:
`
Transaction *Transaction::fromXdrEnvelope(stellar::TransactionEnvelope &xdr)
`

To read from base64 encoded you can use QByteArray::fromBase64 method

Maybe, if it is url encoded, you will have to convert + and / symbols back.

**Comment by munawarb** [comment]
Awesome, thanks for the detailed response, this is exactly what I was looking for :)

**Comment by bnogalm** [comment]
i found out there was a problem serializing hash and return hash memos using fromXdr function. It's solve now.

I close the issue.
