### ISSUE TITLE
Transactions and operations consult using StellarQtSDK

### ISSUE THREAD

**Issue by guarense** [bnogalm/StellarQtSDK#19]
I want to get last 10 transactions in a consult. Each transaction have 5 operations, 4 payments and 1 memotext. Using the library i can get the hash of the transaction. Using the  hash i can get the PagingToken of one operation. I dont know how to get the  PaymentOperationResponse using the librery in order to get the amount. Do I have to captured this information of  using a json consult from the network based on PagingToken? There is cast?
I think that an example would be necesary.

**Comment by bnogalm** [comment]
I agree it requires more examples and documentation, i am working on some small application examples, hope i find time to publish it :/

You are almost there.

A transaction is a set of operations and optionally a memo
Once you have a transaction hash you can use:

PaymentsRequestBuilder &forTransaction(QString transactionId);

And execute it:
OperationPage *execute();

to obtain a OperationPage object

An OperationPage is a Response object with signals:
    void ready();
    void error();

When ready (connect to that signal a slot or lambda) you will be able to access individual Response objects using OperationPage object method .at(index)  and use size() to count them. Also you can use  getRecords() to obtain a QList<Response*>

You will have to cast the Response object to PaymentOperationResponse  using a dynamic_cast, as there can be other types of operations in the same transaction.

The API follows almost same API as Java SDK, the paging thing is one of the things that are a bit different.

**Comment by guarense** [comment]
Thank you very much.
