### ISSUE TITLE
SDK needs to be updated to handle Horizon 0.17.0 breaking changes 

### ISSUE THREAD

**Issue by ire-and-curses** [bnogalm/StellarQtSDK#22]
In Horizon release 0.17.0 (released 26 Feb 2019), several breaking changes were made ([changelog](https://github.com/stellar/go/releases/tag/horizon-v0.17.0)), changing or removing fields that had previously been marked as deprecated.

> Breaking changes
> 
>     Fields removed in this version:
>         Root > protocol_version, use current_protocol_version and core_supported_protocol_version.
>         Ledger > transaction_count, use successful_transaction_count and failed_transaction_count.
>         Signer > public_key, use key.
>     This Horizon version no longer supports Core <10.0.0. Horizon can still ingest version <10 ledgers.
>     Error event name during streaming changed to error to follow W3C specification.
> 

Here is the relevant Horizon commit, showing the fields that were changed: https://github.com/stellar/go/commit/575707ed074a5672438b0f2b788f8b38584ef18d

This is an urgent issue! Any code using this SDK to access a Horizon 0.17.0 server (which includes the SDF public horizon instance at https://horizon.stellar.org/) will be broken until the SDK is updated to match the new response fields.

**Comment by bnogalm** [comment]
I will work on it after work.
If someone needs it before, is only a couple of changes and some of them
are already done.


It seems an invitation to setup our own horizon servers, as i missed the
notification of these breaking changes.

I cant check now if it already exists, but would be nice to implement a
field telling min horizon version supported. So we could use a list of
horizons servers for these cases.

**Comment by ire-and-curses** [comment]
Thanks! Certainly it is true that the public Horizon comes with no SLA, and the most stable (and recommended) course of action is for projects to run their own instances. Nevertheless, we would like to do our best to support your efforts smoothly.

SDF is looking at how to broadcast these changes to relevant maintainers like yourself, and how to work with you to transition through breaking changes safely. I'll follow up here when there is a clear plan.

**Comment by ire-and-curses** [comment]
We have created a keybase channel, `stellar.public #sdk_maintainers`. I'd like to invite you to consider joining. The channel is intended as an informal way for SDF to communicate with community SDK maintainers.

**Comment by bnogalm** [comment]
#24 
Changes are ready to merge.
I will review and test it with my wallet during the weekend.
