### ISSUE TITLE
Sponsorship revocation .h and .cpp files missing

### ISSUE THREAD

**Issue by ElHadjiAlyKane** [bnogalm/StellarQtSDK#54]
Hello. Thank you for working on this SDK which brings us a lot with Stellar. With your latest update to add claimable balances and clawback, when we compile with the new SDK we get file path not found errors and in the folder indexed files are missing:

revokesponsorshipoperationresponse.h
revokeaccountsponsorshipoperation.h
revokeclaimablebalancesponsorshipoperation.h
revokedatasponsorshipoperation.h
revokeoffersponsorshipoperation.h
revokesignersponsorshipoperation.h
revoketrustlinesponsorshipoperation.h

Without forgetting the corresponding .cpp files

**Comment by bnogalm** [comment]
Solved. After so many months i didn't realize i didn't add them to track..

28e13783a1c07ed6dd19e5d0817ae6daf5aa744c

Thanks for the request, i appreciate it. I promise i would take more care if i see more people than me using it.
